
import {
    // Mac
    macbook_air_m1_8gb_256gb_didongviet,
    mac_pro_2023_m2_ultra_didongviet,
    mac_studio_2023_1tb_didongviet,
    mac_studio_2023_512gb_didongviet,
    macbook_air_m2_8gb_256gb_didongviet,
    macbook_air_m2_2023_512gb_sac_70w_didongviet,
    macbook_air_m2_2023_didongviet,
    macbook_pro_m2_didongviet,
    macbook_pro_14_inch_m2_pro_2023_512gb_didongviet_2x,
    macbook_pro_16_inch_m2_max_2023_1tb_didongviet_2x,

    //Iphone
    iphone_11_64gb_chinh_hang_3,
    iphone_11_128gb_chinhhang_didongviet,
    iphone_12_64gb_mau_tim_didongviet,
    iphone_12_128gb_didongviet,
    iphone_13_256gb_didongviet_1,
    iphone_14_256gb_didongviet_1_1,
    iphone_14_512gb_likenew_didongviet_1,
    iphone_14_pro_512gb_didongviet_1,
    iphone_14_pro_max_128gb_didongviet_5,
    iphone_14_pro_max_256gb_didongviet_1_1,
    iphone_14_pro_max_512gb_didongviet_2_1,
    iphone_15_didongviet,
    iphone_15_pro_didongviet,

    //Ipad
    ipad_10_9inch_2022_64gb_5G_didongviet,
    ipad_10_9inch_2022_64gb_wifi_didongviet,
    ipad_10_9inch_2022_256gb_5G,
    ipad_10_9inch_2022_256gb_wifi_didongviet,
    ipad_air_5_2022_M1_64gb_wifi_5G,
    ipad_air_5_2022_M1_64gb_wifi,
    ipad_air_5_2022_M1_256gb_wifi,
    ipad_air5_2022_M1_256gb_wifi_5G,
    ipad_gen_9_2021_64gb_wifi_4g_didongviet,
    ipad_gen_9_2021_64gb_wifi,
    ipad_gen_9_2021_256gb_wifi_4g_didongviet,
    ipad_gen_9_2021_256gb_wifi,
    ipad_mini_6_2021_64gb_wifi_5g,
    ipad_mini_6_2021_64gb_wifi,
    ipad_mini_6_2021_256gb_wifi_5g,
    ipad_mini_6_2021_256gb_wifi,
    ipad_pro_11_inch_2022_m2_256gb_wifi_didongviet_1,
    ipad_pro_11_inch_m2_128gb_5g_didongviet,
    ipad_pro_11_inch_m2_128gb_wifi_didongviet,
    ipad_pro_M2_11inch_2022_1TB_wifi,
    ipad_pro_m2_12_9_inch_256gb_wifi_didongviet,

    // Airpods
    apple_airpods_2_2022_didongviet,
    apple_airpods_3_2022_didongviet,
    apple_airpods_pro_2_2022_didongviet,
    tile_accessibility,
    tile_audio_sharing,
    tile_automatic_switchinge,
    tile_onetap_setup,
    tile_spatial_audio,

    //Watch
    Apple_Watch_SE_2_2022_40_mm_GPS_Viền_nhôm_Dây_cao_su,
    Apple_Watch_SE_2_2022_44_mm_GPS_Viền_nhôm_Dây_cao_su,
    Apple_Watch_Series_8_45_mm_GPS_Dây_cao_su_didongviet_1,
    Apple_Watch_Series_9_41_mm_GPS_Viền_nhôm_Dây_cao_su_size_M_L_didongviet,
    Apple_Watch_Series_9_41_mm_GPS_Viền_nhôm_Dây_cao_su_size_S_M_didongviet,
    Apple_Watch_Series_9_41_mm_LTE_Viền_thép_không_gỉ_Dây_cao_su_size_M_L_didongviet,
    Apple_Watch_Series_9_41_mm_LTE_Viền_thép_không_gỉ_Dây_cao_su_size_S_M_didongviet,
    Apple_Watch_Series_9_41mm_GPS_Viền_nhôm_Dây_quấn_thể_thao_didongviet,
    Apple_Watch_Series_9_45_mm_GPS_Viền_nhôm_Dây_cao_su_size_S_M_didongviet,
    Apple_Watch_Series_9_45_mm_LTE_Viền_nhôm_Dây_cao_su_size_M_L_didongviet,
    Apple_Watch_Series_9_45_mm_LTE_Viền_nhôm_Dây_cao_su_size_S_M_didongviet,
    Apple_Watch_Series_9_45_mm_LTE_Viền_nhôm_Dây_quấn_thể_thao_didongviet,
    Apple_Watch_Series_9_45_mm_LTE_Viền_thép_không_gỉ_Dây_cao_su_size_S_M_didongviet,
    Apple_Watch_Series_9_45_mm_LTE_Viền_thép_không_gỉ_Dây_Milanese_didongviet,
    Apple_Watch_Ultra_2_49_mm_LTE_Viền_Titan_Dây_Alpine_Loop_size_L_didongviet,
    // Apple_Watch_Ultra_2_49_mm_LTE_Viền_Titan_Dây_Alpine_Loop_size_M_didongviet,
    Apple_Watch_Ultra_2_49_mm_LTE_Viền_Titan_Dây_Alpine_Loop_size_S_didongviet,
    Apple_Watch_Ultra_2_49_mm_LTE_Viền_Titan_Dây_Trail_Loop_size_M_L_didongviet,
    Apple_Watch_Ultra_2_49_mm_LTE_Viền_Titan_Dây_Trail_Loop_size_S_M_didongviet,
    Apple_Watch_Ultra2_49_mm_LTE_Viền_Titan_Dây_Ocean_didongviet,
    hero_iphone15,
    hero_iphone15pro,
    hero_apple_watch_series_9,
    watch_logo,
    watch_logo_ultra2,
    promo_apple_watch_ultra2,
    carbon_neutral,
    promo_carbon_neutral,
    logo_watchSE,
    promo_apple_watch_se,
    promo_macbook_air_15,
    promo_ipadpro,
    promo_airpods_pro,
    // Apple_Watch_UCPUltra_2_49_mm_LTE_Viền_Titan_Dây_Alpine_Loop_size_M_didongviet

    // Reviews
    customer1, customer2, customer3

} from '../assets/img/index'

export const navLinks = [
    { href: "/macbook", label: "Macbook" },
    { href: "/ipad", label: "iPad" },
    { href: "/iphone", label: "iPhone" },
    { href: "/watch", label: "Watch" },
    { href: "/airpods", label: "AirPods" },
];

export const reviews = [
    {
        imgURL: customer1,
        customerName: 'Ariana Grande',
        rating: 5,
        feedback: "Sự chú ý đến từng chi tiết và chất lượng của sản phẩm vượt quá sự mong đợi của tôi. Rất khuyến khích!"
    },
    {
        imgURL: customer2,
        customerName: 'The Weeknd',
        rating: 5,
        feedback: "Sản phẩm không chỉ đáp ứng mà còn vượt quá sự mong đợi của tôi. Tôi chắc chắn sẽ là khách hàng quay trở lại!"
    },
    {
        imgURL: customer3,
        customerName: 'Taylor Swift',
        rating: 5,
        feedback: "Sản phẩm không chỉ đáp ứng mà còn vượt quá sự mong đợi của tôi. Rất khuyến khích!"
    }
];
export const Airpods_Carousel = [

    {
        imgURL: tile_accessibility,
        title: 'Thiết lập một chạm'

    }, {
        imgURL: tile_audio_sharing,
        title: 'Âm Thanh Không Gian Cá Nhân Hóa'

    }, {
        imgURL: tile_automatic_switchinge,
        title: 'Chia Sẻ Âm Thanh'

    }, {
        imgURL: tile_onetap_setup,
        title: 'Tự Động Chuyển Đổi'

    }, {
        imgURL: tile_spatial_audio,
        title: 'Trợ Năng'
    }
]

export const HomePage_Hero = [

    {
        // 00
        imgURL: hero_iphone15,
        title: 'iPhone 15 Pro',
        description: 'Titan. Thật bền chắc. Thật nhẹ. Thật Pro.',
    }, {
        //01
        imgURL: hero_iphone15pro,
        title: null,
        description: null

    }, {
        //02
        imgURL: hero_apple_watch_series_9,
        logoURL: watch_logo,
        title: null,
        description: 'Thông minh hơn. Sáng hơn. Quyền năng hơn.'

    }, {
        //03
        imgURL: promo_apple_watch_ultra2,
        logoURL: watch_logo_ultra2,
        title: null,
        description: 'Một đẳng cấp phiêu lưu mới.'

    }, {
        //04
        imgURL: promo_carbon_neutral,
        logoURL: carbon_neutral,
        title: null,
        description: 'Thành tựu đầu tiên từ Apple Watch. Và Apple.'
    }, {
        //05
        imgURL: promo_apple_watch_se,
        logoURL: logo_watchSE,
        title: null,
        description: 'Một mối quá tuyệt.'
    }, {
        //06
        imgURL: promo_macbook_air_15,
        logoURL: null,
        title: ' MacBook Air 15”',
        description: 'Lớn ấn tượng. Mỏng không tưởng.'
    }, {
        //07
        imgURL: promo_ipadpro,
        logoURL: null,
        title: null,
        description: 'Siêu mạnh mẽ với'

    }, {
        //08
        imgURL: promo_airpods_pro,
        logoURL: null,
        title: 'AirPods Pro',
        description: 'Âm Thanh Thích Ứng. Đang phát.'

    },
]
export const Macbook = [
    {
        type: 'Macbook',
        id: '001',
        imgURL: macbook_air_m1_8gb_256gb_didongviet,
        name: "MacBook Air M1 2020 13 inch | 8GB/256GB",
        price: "18.490.000 đ",
        oldPrice: "28.490.000 đ",
        CPU: 'Apple M1 chip with 8-core CPU, 7-core GPU, and 16-core Neural Engine',
        RAM: " 8 GB",
        doPhanGiai: '2560x1600 pixel',
        kichThuocMan: '13-inch Retina display with True Tone',
        DLpin: 'Khoảng 10 tiếng',
        trongLuong: '1.29 Kg',
        kichThuoc: '304.1 x 212.4 x 16.1 mm',
        Colors: ['Xám', 'Vàng', 'Bạc'],
        Capacities: ['256GB']
    },
    {
        type: 'Macbook',
        id: '002',
        imgURL: macbook_air_m2_8gb_256gb_didongviet,
        name: "MacBook Air M2 13-inch 2022 | 8GB/256GB",
        price: "26.090.000 đ",
        oldPrice: "33.990.000 đ",
        CPU: 'Apple M2 (8-Core CPU / 8-Core GPU)',
        RAM: " 8 GB",
        doPhanGiai: '2560x1664 pixels',
        kichThuocMan: '13.6 - Tần số quét 60Hz',
        DLpin: '52.6 Wh',
        trongLuong: '1.24kg',
        kichThuoc: 'Dài 304.1 mm x Ngang 215 mm x Dày 11.3 mm',
        Colors: ['Xám', 'Trắng', 'Bạc', 'Đen'],
        Capacities: ['256GB']
    },
    {
        type: 'Macbook',
        id: '003',
        imgURL: macbook_pro_14_inch_m2_pro_2023_512gb_didongviet_2x,
        name: "MacBook Pro M2 Pro 14 inch 2023 | 16GB/512GB",
        price: "46.990.000 đ",
        oldPrice: "52.990.000 đ",
        CPU: 'Apple M2 Pro (16-Core GPU)',
        RAM: '16 GB',
        doPhanGiai: '3024x1964 pixels',
        kichThuocMan: '14.2 inch - Tần số quét 120Hz',
        DLpin: '18 giờ',
        trongLuong: null,
        kichThuoc: null,
        Colors: ['Xám', 'Bạc']
    },
    {
        type: 'Macbook',
        id: '004',
        imgURL: macbook_pro_m2_didongviet,
        name: "MacBook Pro M2 Max 14 inch 2023 | 32GB/1TB1",
        price: "74.990.000 đ",
        oldPrice: "81.990.000 đ",
        CPU: 'Apple M2 Max (30-Core GPU)',
        RAM: '32 GB',
        doPhanGiai: '3024x1964 pixels',
        kichThuocMan: '14.2 inch - Tần số quét 120Hz',
        DLpin: '18 giờ',
        trongLuong: null,
        kichThuoc: null,
        Colors: ['Xám', 'Bạc']
    },
    {
        type: 'Macbook',
        id: '005',
        imgURL: macbook_pro_16_inch_m2_max_2023_1tb_didongviet_2x,
        name: "MacBook Pro M2 Max 16 inch 2023 | 32GB/1TB",
        price: "84.990.000 đ",
        oldPrice: "91.990.000 đ",
        CPU: 'Apple M2 Max (38-Core GPU)',
        RAM: '32 GB',
        doPhanGiai: '3024x1964 pixels',
        kichThuocMan: '16 inch - Tần số quét 120Hz',
        DLpin: '22 giờ',
        trongLuong: null,
        kichThuoc: null,
        Colors: ['Xám', 'Bạc']
    },
    {
        type: 'Macbook',
        id: '006',
        imgURL: macbook_pro_m2_didongviet,
        name: "MacBook Pro 13-inch 2022 | M2 8GB/256GB",
        price: "28.990.000 đ",
        oldPrice: "35.990.000 đ",
        CPU: 'Apple M2 (10-Core GPU)',
        RAM: '8 GB',
        doPhanGiai: '2560 x 1600 pixels',
        kichThuocMan: '13.3 inch',
        DLpin: '20 giờ',
        trongLuong: '1.4kg',
        kichThuoc: 'dày 1.62cm',
        Colors: ['Xám', 'Bạc']
    },
    {
        type: 'Macbook',
        id: '007',
        imgURL: macbook_air_m2_2023_didongviet,
        name: "MacBook Air M2 15-inch 2023 | 8GB/256GB",
        price: "31.390.000 đ",
        oldPrice: "32.990.000 đ",
        CPU: 'Apple M2 (10-core GPU)',
        RAM: '8 GB',
        doPhanGiai: '2880x1864 pixels',
        kichThuocMan: '15.3 inch',
        DLpin: '18 giờ',
        trongLuong: '1.51kg',
        kichThuoc: 'Dài 340.4 mm - Rộng 237.6 mm - Dày 11.5 mm',
        Colors: ['Xám', 'Bạc', 'Vàng', 'Xanh đen']
    },
    {
        type: 'Macbook',
        id: '008',
        imgURL: mac_studio_2023_512gb_didongviet,
        name: "Mac Studio M2 Max 2023 | 32GB/512GB",
        price: "54.990.000 đ",
        oldPrice: null,
        CPU: 'Apple M2 Max (30-Core GPU)',
        RAM: '32 GB',
        doPhanGiai: null,
        kichThuocMan: '27 inch',
        DLpin: '22 giờ',
        trongLuong: null,
        kichThuoc: null,
        Colors: ['Xám', 'Bạc']
    },
    {
        type: 'Macbook',
        id: '009',
        imgURL: mac_studio_2023_1tb_didongviet,
        name: "MacBook Air M2 15-inch 2023 | 8GB/256GB",
        price: "109.990.000 đ",
        oldPrice: null,
        CPU: 'Apple M2 Ultra (60-Core GPU)',
        RAM: '64 GB',
        doPhanGiai: null,
        kichThuocMan: '27 inch',
        DLpin: '22 giờ',
        trongLuong: null,
        kichThuoc: null,
        Colors: ['Xám', 'Bạc']
    },
    {
        type: 'Macbook',
        id: '010',
        imgURL: mac_pro_2023_m2_ultra_didongviet,
        name: "Mac Pro M2 Ultra 2023 | 64GB/1TB",
        price: "179.990.000 đ",
        oldPrice: null,
        CPU: 'Apple M2 Ultra (60-Core GPU)',
        RAM: '64 GB',
        doPhanGiai: null,
        kichThuocMan: '32 inch',
        DLpin: '22 giờ',
        trongLuong: null,
        kichThuoc: null,
        Colors: ['Xám', 'Bạc']
    },
    {
        type: 'Macbook',
        id: '011',
        imgURL: macbook_air_m2_2023_512gb_sac_70w_didongviet,
        name: "MacBook Air M2 15-inch 2023 | 8GB/512GB (Sạc 70W)",
        price: "36.990.000 đ",
        oldPrice: "37.990.000 đ",
        CPU: 'Apple M2 (10-Core GPU)',
        RAM: '8 GB',
        doPhanGiai: null,
        kichThuocMan: '15.3 inch',
        DLpin: '18 giờ',
        trongLuong: null,
        kichThuoc: null,
        Colors: ['Xám', 'Bạc']
    },
];



export const Iphone = [
    {
        type: 'Iphone',
        id: '001',
        imgURL: iphone_11_64gb_chinh_hang_3,
        name: "Iphone 11 64GB Chính Hãng (VN/A)",
        price: "10.390.000 đ",
        oldPrice: "14.990.000 đ",
        CPU: 'Apple A13 Bionic',
        RAM: '4 GB',
        doPhanGiai: '828 x 1792 pixels',
        kichThuocMan: '6.1 inch',
        DLpin: '3110 mAh',
        trongLuong: '194g',
        kichThuoc: '150.9 x 75.7 x 8.3 mm',
        Colors: ['Trắng', 'Đen', 'Tím', 'Vàng', 'Đỏ', 'Xanh']
    },
    {
        type: 'Iphone',
        id: '002',
        imgURL: iphone_11_128gb_chinhhang_didongviet,
        name: "Iphone 11 128GB Chính Hãng (VN/A)",
        price: "11.890.000 đ",
        oldPrice: "16.990.000 đ",
        CPU: 'Apple A13 Bionic',
        RAM: '4 GB',
        doPhanGiai: '828 x 1792 pixels',
        kichThuocMan: '6.1 inch',
        DLpin: '3110 mAh',
        trongLuong: '194g',
        kichThuoc: '150.9 x 75.7 x 8.3 mm',
        Colors: ['Trắng', 'Đen', 'Tím', 'Vàng', 'Đỏ', 'Xanh']
    },
    {
        type: 'Iphone',
        id: '003',
        imgURL: iphone_12_64gb_mau_tim_didongviet,
        name: "Iphone 12 64GB Chính Hãng (VN/A)",
        price: "14.890.000 đ",
        oldPrice: "17.990.000 đ",
        CPU: 'Apple A14 Bionic (5nm CPU), Apple GPU (4-Core graphics)',
        RAM: '4 GB',
        doPhanGiai: '1170x2532 pixels',
        kichThuocMan: '6.1 inch',
        DLpin: '2815 mAh',
        trongLuong: '164g',
        kichThuoc: 'Dài 146.7 mm - Ngang 71.5 mm - Dày 7.4 mm',
        Colors: ['Trắng', 'Đen', 'Tím', 'Vàng', 'Đỏ', 'Xanh']
    },
    {
        type: 'Iphone',
        id: '004',
        imgURL: iphone_12_128gb_didongviet,
        name: "Iphone 12 128GB Chính Hãng (VN/A)",
        price: "14.790.000 đ",
        oldPrice: "18.790.000 đ",
        CPU: 'Apple A14 Bionic (5nm CPU), Apple GPU (4-Core graphics)',
        RAM: '4 GB',
        doPhanGiai: '1170x2532 pixels',
        kichThuocMan: '6.1 inch',
        DLpin: '2815 mAh',
        trongLuong: '164g',
        kichThuoc: 'Dài 146.7 mm - Ngang 71.5 mm - Dày 7.4 mm',
        Colors: ['Trắng', 'Đen', 'Tím', 'Vàng', 'Đỏ', 'Xanh']
    },
    {
        type: 'Iphone',
        id: '005',
        imgURL: iphone_13_256gb_didongviet_1,
        name: "Iphone 13 256GB Chính Hãng (VN/A)",
        price: "21.290.000 đ",
        oldPrice: "27.990.000 đ",
        CPU: 'Apple A15 Bionic',
        RAM: '4 GB',
        doPhanGiai: '1170x2532 pixels',
        kichThuocMan: '6.1 inch - Tần số quét 60Hz',
        DLpin: null,
        trongLuong: '164g',
        kichThuoc: '146.7 x 71.5 x 7.4 mm',
        Colors: ['Trắng', 'Đen', 'Tím', 'Vàng', 'Đỏ', 'Xanh']
    },
    {
        type: 'Iphone',
        id: '006',
        imgURL: iphone_14_256gb_didongviet_1_1,
        name: "Iphone 14 256GB Chính Hãng (VN/A)",
        price: "21.890.000 đ",
        oldPrice: "27.990.000 đ",
        CPU: 'Apple A15 Bionic 6 nhân, GPU 5 nhân',
        RAM: '6 GB',
        doPhanGiai: '1170x2532 pixels',
        kichThuocMan: '6.1 inch - Tần số quét 60Hz',
        DLpin: null,
        trongLuong: '172g',
        kichThuoc: 'Dài 146.7 mm - Ngang 71.5 mm - Dày 7.8 mm',
        Colors: ['Tím', 'Vàng', 'Xám', 'Bạc']
    },
    {
        type: 'Iphone',
        id: '007',
        imgURL: iphone_14_512gb_likenew_didongviet_1,
        name: "Iphone 14 512GB Chính Hãng (VN/A)",
        price: "23.290.000 đ",
        oldPrice: "33.990.000",
        CPU: 'Apple A15 Bionic 6 nhân, GPU 5 nhân',
        RAM: '6 GB',
        doPhanGiai: '1170x2532 pixels',
        kichThuocMan: '6.1 inch - Tần số quét 60Hz',
        DLpin: null,
        trongLuong: '172g',
        kichThuoc: 'Dài 146.7 mm - Ngang 71.5 mm - Dày 7.8 mm',
        Colors: ['Tím', 'Vàng', 'Xám', 'Bạc']
    },
    {
        type: 'Iphone',
        id: '008',
        imgURL: iphone_14_pro_512gb_didongviet_1,
        name: "Iphone 14 Pro 512GB Chính Hãng (VN/A)",
        price: "31.990.000 đ",
        oldPrice: "39.990.000 đ",
        CPU: 'Apple A15 Bionic 6 nhân, GPU 5 nhân',
        RAM: '6 GB',
        doPhanGiai: '1170x2532 pixels',
        kichThuocMan: '6.1 inch - Tần số quét 120Hz',
        DLpin: null,
        trongLuong: '206g',
        kichThuoc: 'Dài 147.5 mm - Ngang 71.5 mm - Dày 7.85 mm',
        Colors: ['Tím', 'Vàng', 'Xám', 'Bạc']
    },
    {
        type: 'Iphone',
        id: '009',
        imgURL: iphone_14_pro_max_128gb_didongviet_5,
        name: "Iphone 14 Pro Max 128GB Chính Hãng (VN/A)",
        price: "25.690.000 đ",
        oldPrice: "33.990.000 đ",
        CPU: 'Apple A16 Bionic 6 nhân, GPU 5 nhân',
        RAM: '6 GB',
        doPhanGiai: '1290 x 2796 pixels',
        kichThuocMan: '6.7 inch - Tần số quét 120Hz',
        DLpin: null,
        trongLuong: '240g',
        kichThuoc: 'Dài 160.7 mm - Ngang 77.6 mm - Dày 7.85 mm',
        Colors: ['Tím', 'Vàng', 'Xám', 'Bạc']
    },
    {
        type: 'Iphone',
        id: '010',
        imgURL: iphone_14_pro_max_256gb_didongviet_1_1,
        name: "Iphone 14 Pro Max 256GB Chính Hãng (VN/A)",
        price: "28.590.000 đ",
        oldPrice: "37.990.000 đ",
        CPU: 'Apple A16 Bionic 6 nhân, GPU 5 nhân',
        RAM: '6 GB',
        doPhanGiai: '1290 x 2796 pixels',
        kichThuocMan: '6.7 inch - Tần số quét 120Hz',
        DLpin: null,
        trongLuong: '240g',
        kichThuoc: 'Dài 160.7 mm - Ngang 77.6 mm - Dày 7.85 mm',
        Colors: ['Tím', 'Vàng', 'Xám', 'Bạc']
    },
    {
        type: 'Iphone',
        id: '011',
        imgURL: iphone_14_pro_max_512gb_didongviet_2_1,
        name: "Iphone 14 Pro Max 512GB Chính Hãng (VN/A)",
        price: "35.790.000 đ",
        oldPrice: "43.990.000 đ",
        CPU: 'Apple A16 Bionic 6 nhân, GPU 5 nhân',
        RAM: '6 GB',
        doPhanGiai: '1290 x 2796 pixels',
        kichThuocMan: '6.7 inch - Tần số quét 120Hz',
        DLpin: null,
        trongLuong: '240g',
        kichThuoc: 'Dài 160.7 mm - Ngang 77.6 mm - Dày 7.85 mm',
        Colors: ['Tím', 'Vàng', 'Xám', 'Bạc']
    }, {
        type: 'Iphone',
        id: '012',
        imgURL: iphone_15_pro_didongviet,
        name: "iPhone 15 Pro Max 256GB Chính hãng (VN/A)",
        price: "34.490.000 đ",
        oldPrice: "38.990.000 đ",
        CPU: 'A17 Pro,Apple GPU 6 nhân',
        RAM: '256GB',
        doPhanGiai: '2796 x 1290 pixel',
        kichThuocMan: '6.7 inch - Tần số quét 120Hz',
        DLpin: "4422mAh",
        trongLuong: '221 grams',
        kichThuoc: 'Dài 159.9 mm - Ngang 76.7 mm - Dày 8.25 mm',
        Colors: ['Titan Xanh', 'Titan Đen', 'Titan Trắng', 'Titan tự nhiên']
    }, {
        type: 'Iphone',
        id: '013',
        imgURL: iphone_15_didongviet,
        name: "iPhone 15 128GB Chính hãng (VN/A)",
        price: "21.790.000 đ",
        oldPrice: "22.990.000 đ",
        CPU: 'A17 Pro,Apple GPU 6 nhân',
        RAM: '256GB',
        doPhanGiai: '2556 x 1179 pixels',
        kichThuocMan: '6.1 inch - Tần số quét 120Hz',
        DLpin: "3349mAh",
        trongLuong: '171 grams',
        kichThuoc: 'Dài 147.6 mm - Ngang 71.6 mm - Dày 7.80 mm',
        Colors: ['Xanh dương', 'Vàng', 'Đen', 'Xanh lá', 'Hồng']
    },
];


export const Ipad = [
    {
        type: 'Ipad',
        id: '001',
        imgURL: ipad_10_9inch_2022_64gb_5G_didongviet,
        name: "Ipad 10.9-inch 2022 | 64GB 5G",
        price: "13.890.000 đ",
        oldPrice: "17.990.000 đ",
        CPU: 'Apple A14 Bionic CPU, GPU 4 nhân',
        RAM: '4 GB',
        doPhanGiai: '1640 x 2360 pixels',
        kichThuocMan: '10.9 inch - Tần số quét 60Hz',
        DLpin: '28.6 Wh',
        trongLuong: '481g',
        kichThuoc: 'Dài 248.6 mm - Ngang 179.5 mm - Dày 7 mm',
        Colors: ['Bạc', 'Xanh', 'Hồng', 'Vàng']
    },
    {
        type: 'Ipad',
        id: '002',
        imgURL: ipad_10_9inch_2022_64gb_wifi_didongviet,
        name: "Ipad 10.9-inch 2022 | 64GB Wifi",
        price: "10.490.000 đ",
        oldPrice: "12.990.000 đ",
        CPU: 'Apple GPU 4 nhân và CPU 2 nhân 2.65 GHz & 4 nhân 1.8 GHz',
        RAM: '4 GB',
        doPhanGiai: '1640 x 2360 pixels',
        kichThuocMan: '10.9 inch - Tần số quét 60Hz',
        DLpin: '28.6 Wh',
        trongLuong: '477g',
        kichThuoc: 'Dài 248.6 mm - Ngang 179.5 mm - Dày 7 mm',
        Colors: ['Bạc', 'Xanh', 'Hồng', 'Vàng']
    },
    {
        type: 'Ipad',
        id: '003',
        imgURL: ipad_10_9inch_2022_256gb_5G,
        name: "Ipad 10.9-inch 2022 | 256GB 5G",
        price: "18.490.000 đ",
        oldPrice: "21.990.000 đ",
        CPU: 'Apple GPU 4 nhân và CPU 2 nhân 2.65 GHz & 4 nhân 1.8 GHz',
        RAM: '4 GB',
        doPhanGiai: '1640 x 2360 pixels',
        kichThuocMan: '10.9 inch - Tần số quét 60Hz',
        DLpin: '28.6 Wh',
        trongLuong: '477g',
        kichThuoc: 'Dài 248.6 mm - Ngang 179.5 mm - Dày 7 mm',
        Colors: ['Bạc', 'Xanh', 'Hồng', 'Vàng']
    },
    {
        type: 'Ipad',
        id: '004',
        imgURL: ipad_10_9inch_2022_256gb_wifi_didongviet,
        name: "Ipad 10.9-inch 2022 | 256GB Wifi",
        price: "14.590.000 đ",
        oldPrice: "17.990.000 đ",
        CPU: 'Apple GPU 4 nhân và CPU 2 nhân 2.65 GHz & 4 nhân 1.8 GHz',
        RAM: '4 GB',
        doPhanGiai: '1640 x 2360 pixels',
        kichThuocMan: '10.9 inch - Tần số quét 60Hz',
        DLpin: '28.6 Wh',
        trongLuong: '477g',
        kichThuoc: 'Dài 248.6 mm - Ngang 179.5 mm - Dày 7 mm',
        Colors: ['Bạc', 'Xanh', 'Hồng', 'Vàng']
    },
    {
        type: 'Ipad',
        id: '005',
        imgURL: ipad_air_5_2022_M1_64gb_wifi_5G,
        name: "Ipad Air 5 2022 | M1 64GB Wifi & 5G",
        price: "17.390.000 đ",
        oldPrice: "21.990.000 đ",
        CPU: 'Apple A15 Bionic CPU và GPU 4 nhân',
        RAM: '8 GB',
        doPhanGiai: '1640 x 2360 pixels',
        kichThuocMan: '10.9 inches',
        DLpin: 'khoảng 7587 mAh',
        trongLuong: '462g',
        kichThuoc: 'Dài 247.6 mm - Ngang 178.5 mm - Dày 6.1 mm',
        Colors: ['Xám', 'Xanh', 'Hồng', 'Bạc', 'Tím']
    },
    {
        type: 'Ipad',
        id: '006',
        imgURL: ipad_air_5_2022_M1_64gb_wifi,
        name: "Ipad Air 5 2022 | M1 64GB Wifi",
        price: "13.390.000 đ",
        oldPrice: "16.990.000 đ",
        CPU: 'Apple M1 CPU và GPU 4 nhân',
        RAM: '8 GB',
        doPhanGiai: '1640 x 2360 pixels',
        kichThuocMan: '10.9 inches',
        DLpin: 'khoảng 7587 mAh',
        trongLuong: '461g',
        kichThuoc: 'Dài 247.6 mm - Ngang 178.5 mm - Dày 6.1 mm',
        Colors: ['Xám', 'Xanh', 'Hồng', 'Bạc', 'Tím']
    },
    {
        type: 'Ipad',
        id: '007',
        imgURL: ipad_air_5_2022_M1_256gb_wifi,
        name: "Ipad Air 5 2022 | M1 256GB Wifi",
        price: "17.790.000 đ",
        oldPrice: "21.990.000 đ",
        CPU: 'Apple M1 CPU và GPU 4 nhân',
        RAM: '8 GB',
        doPhanGiai: '1640 x 2360 pixels',
        kichThuocMan: '10.9 inches',
        DLpin: 'khoảng 7587 mAh',
        trongLuong: '461g',
        kichThuoc: 'Dài 247.6 mm - Ngang 178.5 mm - Dày 6.1 mm',
        Colors: ['Xám', 'Xanh', 'Hồng', 'Bạc', 'Tím']
    },
    {
        type: 'Ipad',
        id: '008',
        imgURL: ipad_air5_2022_M1_256gb_wifi_5G,
        name: "Ipad Air 5 2022 | M1 256GB Wifi & 5G",
        price: "23.290.000 đ",
        oldPrice: "24.990.000 đ",
        CPU: 'Apple A15 Bionic và GPU 4 nhân',
        RAM: '8 GB',
        doPhanGiai: '1640 x 2360 pixels',
        kichThuocMan: '10.9 inches',
        DLpin: 'khoảng 7587 mAh',
        trongLuong: '462g',
        kichThuoc: 'Dài 247.6 mm - Ngang 178.5 mm - Dày 6.1 mm',
        Colors: ['Xám', 'Xanh', 'Hồng', 'Bạc', 'Tím']
    },
    {
        type: 'Ipad',
        id: '009',
        imgURL: ipad_gen_9_2021_64gb_wifi_4g_didongviet,
        name: "Ipad Gen 9 2021 | Wifi & 4G 64GB",
        price: "9.490.000 đ",
        oldPrice: null,
        CPU: 'Apple A13 Bionic 6 nhân CPU và GPU 2 nhân 2.65 GHz & 4 nhân 1.8 Hz',
        RAM: '3 GB',
        doPhanGiai: '1640 x 2160 pixels',
        kichThuocMan: '10.2 ',
        DLpin: '32.4 Wh',
        trongLuong: '487g',
        kichThuoc: '250.6 x 174.1 x 7.5 mm',
        Colors: ['Xám', 'Bạc']
    },
    {
        type: 'Ipad',
        id: '010',
        imgURL: ipad_gen_9_2021_64gb_wifi,
        name: "Ipad Gen 9 2021 | Wifi 64GB",
        price: "6.790.000 đ",
        oldPrice: "9.990.000 đ",
        CPU: 'Apple A13 Bionic',
        RAM: '3 GB',
        doPhanGiai: '1640 x 2160 pixels',
        kichThuocMan: '10.2 inch',
        DLpin: '32.4 Wh',
        trongLuong: '487g',
        kichThuoc: '250.6 x 174.1 x 0.29 mm',
        Colors: ['Xám', 'Bạc']
    },
    {
        type: 'Ipad',
        id: '011',
        imgURL: ipad_gen_9_2021_256gb_wifi_4g_didongviet,
        name: "Ipad Gen 9 2021 | Wifi & 4G 256GB",
        price: "16.390.000 đ",
        oldPrice: null,
        CPU: 'Apple A13 Bionic 6 nhân',
        RAM: '3 GB',
        doPhanGiai: '1620 x 2160 pixels',
        kichThuocMan: '10.2 inch',
        DLpin: '32.4 Wh',
        trongLuong: '487g',
        kichThuoc: '250.6 x 174.1 x 7.5 mm',
        Colors: ['Xám', 'Bạc']
    },
    {
        type: 'Ipad',
        id: '012',
        imgURL: ipad_gen_9_2021_256gb_wifi,
        name: "Ipad Gen 9 2021 | Wifi 256GB",
        price: "11.290.000 đ",
        oldPrice: "14.990.000 đ",
        CPU: 'Apple A13 Bionic 6 nhân',
        RAM: '3 GB',
        doPhanGiai: '1620 x 2160 pixels',
        kichThuocMan: '10.2 inch',
        DLpin: '32.4 Wh',
        trongLuong: '487g',
        kichThuoc: '250.6 x 174.1 x 7.5 mm',
        Colors: ['Xám', 'Bạc']
    },
    {
        type: 'Ipad',
        id: '013',
        imgURL: ipad_mini_6_2021_64gb_wifi_5g,
        name: "Ipad mini 6 2021 | 64GB Wifi & 5G",
        price: "15.290.000 đ",
        oldPrice: null,
        CPU: 'Apple A15 Bionic 6 nhân',
        RAM: '4 GB',
        doPhanGiai: '2266 x 1488 pixels',
        kichThuocMan: '8.3 inch',
        DLpin: '19.3 Wh',
        trongLuong: '487g',
        kichThuoc: 'Dài 195.4 mm - Ngang 134.8 mm - Dày 6.3 mm'
    },
    {
        type: 'Ipad',
        id: '014',
        imgURL: ipad_mini_6_2021_64gb_wifi,
        name: "Ipad mini 6 2021 | 64GB Wifi",
        price: "10.990.000 đ",
        oldPrice: "16.790.000 đ",
        CPU: 'Apple A15 Bionic',
        RAM: '4 GB',
        doPhanGiai: '2266 x 1488 pixels',
        kichThuocMan: '8.3 inch',
        DLpin: null,
        trongLuong: null,
        kichThuoc: '195.4 x 134.8 x 6.3mm',
        Colors: ['Hồng', 'Bạc', 'Xám đen', 'Tím']
    },
    {
        type: 'Ipad',
        id: '015',
        imgURL: ipad_mini_6_2021_256gb_wifi_5g,
        name: "Ipad mini 6 2021 | 256GB Wifi & 5G",
        price: "19.990.000 đ",
        oldPrice: null,
        CPU: 'Apple A15 Bionic',
        RAM: '4 GB',
        doPhanGiai: '2048 x 1536 pixels',
        kichThuocMan: '8.5 inch',
        DLpin: null,
        trongLuong: null,
        kichThuoc: '206 x 138 x 6.1 mm',
        Colors: ['Hồng', 'Bạc', 'Xám đen', 'Tím']
    },
    {
        type: 'Ipad',
        id: '016',
        imgURL: ipad_mini_6_2021_256gb_wifi,
        name: "Ipad mini 6 2021 | 256GB Wifi",
        price: "16.790.000 đ",
        oldPrice: null,
        CPU: 'Apple A15 Bionic',
        RAM: '4 GB',
        doPhanGiai: '2266 x 1488 pixels',
        kichThuocMan: '8.3 inch',
        DLpin: null,
        trongLuong: null,
        kichThuoc: '195.4 x 134.8 x 6.3mm',
        Colors: ['Hồng', 'Bạc', 'Xám đen', 'Tím']
    },
    {
        type: 'Ipad',
        id: '017',
        imgURL: ipad_pro_11_inch_2022_m2_256gb_wifi_didongviet_1,
        name: "Ipad Pro M2 11-inch (2022) | 256GB Wifi",
        price: "23.190.000 đ",
        oldPrice: "25.990.000 đ",
        CPU: null,
        RAM: '8 GB',
        doPhanGiai: '1668 x 2388 pixels',
        kichThuocMan: '11 inch',
        DLpin: null,
        trongLuong: null,
        kichThuoc: null,
        Colors: ['Hồng', 'Bạc', 'Xám đen', 'Tím']
    },
    {
        type: 'Ipad',
        id: '018',
        imgURL: ipad_pro_11_inch_m2_128gb_5g_didongviet,
        name: "Ipad Pro M2 11-inch (2022) | 128Gb 5G",
        price: "23.290.000 đ",
        oldPrice: "28.990.000 đ",
        CPU: null,
        RAM: '8 GB',
        doPhanGiai: '1668 x 2388 pixels',
        kichThuocMan: '11 inch',
        DLpin: null,
        trongLuong: null,
        kichThuoc: null,
        Colors: ['Hồng', 'Bạc', 'Xám đen', 'Tím']
    },
    {
        type: 'Ipad',
        id: '019',
        imgURL: ipad_pro_11_inch_m2_128gb_wifi_didongviet,
        name: "Ipad Pro M2 11-inch (2022) | 128GB Wifi",
        price: "19.550.000 đ",
        oldPrice: "21.990.000 đ",
        CPU: null,
        RAM: '8 GB',
        doPhanGiai: '1668 x 2388 pixels',
        kichThuocMan: '11 inches',
        DLpin: null,
        trongLuong: null,
        kichThuoc: null,
        Colors: ['Hồng', 'Bạc', 'Xám đen', 'Tím']
    },
    {
        type: 'Ipad',
        id: '020',
        imgURL: ipad_pro_M2_11inch_2022_1TB_wifi,
        name: "Ipad Pro M2 11-inch (2022) | 1TB Wifi",
        price: "38.990.000 đ",
        oldPrice: "43.990.000 đ",
        CPU: null,
        RAM: '8 GB',
        doPhanGiai: '1668 x 2388 pixels',
        kichThuocMan: '11 inches',
        DLpin: null,
        trongLuong: null,
        kichThuoc: null,
        Colors: ['Hồng', 'Bạc', 'Xám đen', 'Tím']
    },
    {
        type: 'Ipad',
        id: '021',
        imgURL: ipad_pro_m2_12_9_inch_256gb_wifi_didongviet,
        name: "Ipad Pro M2 12.9-inch (2022) | 256GB Wifi",
        price: "30.990.000 đ",
        oldPrice: "34.990.000 đ",
        CPU: null,
        RAM: '8 GB',
        doPhanGiai: '1668 x 2388 pixels',
        kichThuocMan: '12.9 inches - Tần số quét 120Hz',
        DLpin: null,
        trongLuong: null,
        kichThuoc: null,
        Colors: ['Hồng', 'Bạc', 'Xám đen', 'Tím']
    },
];


export const AirPods = [
    {
        type: 'AirPods',
        id: '001',
        imgURL: apple_airpods_2_2022_didongviet,
        name: "Tai nghe Apple AirPods 2 Chính Hãng (VN/A) (No Wireless Charge)",
        price: "2.590.000 đ",
        oldPrice: "3.990.000 đ",
        CPU: 'Chip H1',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: null,
        DLpin: 'Trên 24 tiếng',
        trongLuong: 'hộp sạc 38.2g',
        kichThuoc: '16.5 x 18.0 x 40.5 mm'
    },
    {
        type: 'AirPods',
        id: '002',
        imgURL: apple_airpods_pro_2_2022_didongviet,
        name: "Tai nghe Apple AirPods Pro 2 2022 Chính Hãng",
        price: "5.690.000 đ",
        oldPrice: "6.990.000",
        CPU: 'Chip H2',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: null,
        DLpin: 'Trên 24 tiếng',
        trongLuong: 'tai nghe 5.3g, hộp sạc 38.2g',
        kichThuoc: 'Dài 30.9 mm x Rộng 21.8 mm x Dày 24 mm'
    },
    {
        type: 'AirPods',
        id: '003',
        imgURL: apple_airpods_3_2022_didongviet,
        name: "Tai nghe Apple AirPods 3 2022 Lightning Chính Hãng",
        price: "4.190.000 đ",
        oldPrice: "5.490.000 đ",
        CPU: 'Chip H1',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: null,
        DLpin: 'khoảng 6 giờ kèm hộp sạc 30 giờ',
        trongLuong: '4.28 gram (mỗi tai nghe)',
        kichThuoc: '30.79 x 18.26 x 19.21 mm'
    },
];



export const Watch = [
    {
        type: 'Watch',
        id: '001',
        imgURL: Apple_Watch_SE_2_2022_40_mm_GPS_Viền_nhôm_Dây_cao_su,
        name: "Apple Watch SE 2 (2022) 40mm (GPS) Viền nhôm - Dây cao su",
        price: "5.790.000 đ",
        oldPrice: "7.490.000 đ",
        CPU: 'Apple S8',
        RAM: null,
        doPhanGiai: '448 x 368 pixels',
        kichThuocMan: '1.78 inches',
        DLpin: null,
        trongLuong: '26.4g',
        kichThuoc: '40 mm - 34 mm - 10.7 mm'
    },
    {
        type: 'Watch',
        id: '002',
        imgURL: Apple_Watch_SE_2_2022_44_mm_GPS_Viền_nhôm_Dây_cao_su,
        name: "Apple Watch SE 2 (2022) 44mm (GPS) Viền nhôm - Dây cao su",
        price: "6.590.000 đ",
        oldPrice: "8.490.000 đ",
        CPU: 'Apple S8',
        RAM: null,
        doPhanGiai: '448 x 368 pixels',
        kichThuocMan: '1.78 inches',
        DLpin: null,
        trongLuong: '33g',
        kichThuoc: '44 x 38 x 10.7 mm'
    },
    {
        type: 'Watch',
        id: '003',
        imgURL: Apple_Watch_Series_8_45_mm_GPS_Dây_cao_su_didongviet_1,
        name: "Apple Watch Series 8 45mm (GPS) Dây cao su",
        price: "9.590.000 đ",
        oldPrice: "12.990.000 đ",
        CPU: 'Apple S8 - Lõi kép',
        RAM: null,
        doPhanGiai: '430 x 352 pixels',
        kichThuocMan: '1.9 inches',
        DLpin: null,
        trongLuong: '38.8g',
        kichThuoc: '45 x 38 x 10,7 mm'
    },
    {
        type: 'Watch',
        id: '004',
        imgURL: Apple_Watch_Series_9_41_mm_GPS_Viền_nhôm_Dây_cao_su_size_M_L_didongviet,
        name: "Apple Watch Series 9 41mm (GPS) Viền nhôm - Dây cao su size M/L",
        price: "10.490.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.9 inches',
        DLpin: null,
        trongLuong: null,
        kichThuoc: '41 x 35 x 10,7 mm'
    },
    {
        type: 'Watch',
        id: '005',
        imgURL: Apple_Watch_Series_9_41_mm_GPS_Viền_nhôm_Dây_cao_su_size_S_M_didongviet,
        name: "Apple Watch Series 9 41mm (GPS) Viền nhôm - Dây cao su size S/M",
        price: "10.490.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.9 inch',
        DLpin: 'lên đến 18 giờ, 36 giờ ở chế độ nguồn điện thấp',
        trongLuong: null,
        kichThuoc: '41 x 35 x 10,7 mm'
    },
    {
        type: 'Watch',
        id: '006',
        imgURL: Apple_Watch_Series_9_41_mm_LTE_Viền_thép_không_gỉ_Dây_cao_su_size_M_L_didongviet,
        name: "Apple Watch Series 9 41mm (LTE) Viền thép không gỉ - Dây cao su size M/L",
        price: "18.990.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.9 inch',
        DLpin: null,
        trongLuong: null,
        kichThuoc: '41 x 35 x 10,7 mm'
    },
    {
        type: 'Watch',
        id: '007',
        imgURL: Apple_Watch_Series_9_41_mm_LTE_Viền_thép_không_gỉ_Dây_cao_su_size_S_M_didongviet,
        name: "Apple Watch Series 9 41mm (LTE) Viền thép không gỉ - Dây cao su size S/M",
        price: "18.990.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.9 inch',
        DLpin: null,
        trongLuong: null,
        kichThuoc: '41 x 35 x 10,7 mm'
    },
    {
        type: 'Watch',
        id: '008',
        imgURL: Apple_Watch_Series_9_41mm_GPS_Viền_nhôm_Dây_quấn_thể_thao_didongviet,
        name: "Apple Watch Series 9 41mm (GPS) Viền nhôm - Dây quấn thể thao",
        price: "10.490.000 đ",
        CPU: null,
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: null,
        DLpin: null,
        trongLuong: null,
        kichThuoc: null
    },
    {
        type: 'Watch',
        id: '009',
        imgURL: Apple_Watch_Series_9_45_mm_GPS_Viền_nhôm_Dây_cao_su_size_S_M_didongviet,
        name: "Apple Watch Series 9 45mm (GPS) Viền nhôm - Dây cao su size S/M",
        price: "11.290.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.9 inch',
        DLpin: null,
        trongLuong: null,
        kichThuoc: '45 x 38 x 10,7 mm'
    },
    {
        type: 'Watch',
        id: '010',
        imgURL: Apple_Watch_Series_9_45_mm_LTE_Viền_nhôm_Dây_cao_su_size_M_L_didongviet,
        name: "Apple Watch Series 9 45mm (LTE) Viền nhôm - Dây cao su size M/L",
        price: "13.890.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.9 inch',
        DLpin: null,
        trongLuong: null,
        kichThuoc: '45 x 38 x 10,7 mm'
    },
    {
        type: 'Watch',
        id: '011',
        imgURL: Apple_Watch_Series_9_45_mm_LTE_Viền_nhôm_Dây_cao_su_size_S_M_didongviet,
        name: "Apple Watch Series 9 45mm (LTE) Viền nhôm - Dây cao su size S/M",
        price: "13.890.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.9 inch',
        DLpin: 'Lên đến 18 giờ, Lên đến 36 giờ ở Chế Độ Nguồn Điện Thấp',
        trongLuong: null,
        kichThuoc: '45 x 38 x 10,7 mm'
    },
    {
        type: 'Watch',
        id: '012',
        imgURL: Apple_Watch_Series_9_45_mm_LTE_Viền_nhôm_Dây_quấn_thể_thao_didongviet,
        name: "Apple Watch Series 9 45mm (LTE) Viền nhôm - Dây quấn thể thao",
        price: "13.890.000 đ",
        CPU: null,
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: null,
        DLpin: null,
        trongLuong: null,
        kichThuoc: null
    },
    {
        type: 'Watch',
        id: '013',
        imgURL: Apple_Watch_Series_9_45_mm_LTE_Viền_thép_không_gỉ_Dây_cao_su_size_S_M_didongviet,
        name: "Apple Watch Series 9 45mm (LTE) Viền thép không gỉ - Dây cao su size S/M",
        price: "20.290.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.9 inch',
        DLpin: null,
        trongLuong: '38.8 gram',
        kichThuoc: '45 x 38 x 10,7 mm'
    },
    {
        type: 'Watch',
        id: '014',
        imgURL: Apple_Watch_Series_9_45_mm_LTE_Viền_thép_không_gỉ_Dây_Milanese_didongviet,
        name: "Apple Watch Series 9 45mm (LTE) Viền thép không gỉ - Dây Milanese",
        price: "20.290.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.9 inch',
        DLpin: null,
        trongLuong: '38.8 gram',
        kichThuoc: '45 x 38 x 10,7 mm'
    },
    {
        type: 'Watch',
        id: '015',
        imgURL: Apple_Watch_Ultra_2_49_mm_LTE_Viền_Titan_Dây_Alpine_Loop_size_L_didongviet,
        name: "Apple Watch Ultra 2 49mm (LTE) Viền Titan - Dây Alpine Loop size L",
        price: "21.990.000 đ",

    },
    // {
    //     type: 'Watch',
    //     id: '016',
    //     imgURL: Apple_Watch_UCPUltra_2_49_mm_LTE_Viền_Titan_Dây_Alpine_Loop_size_M_didongviet,
    //     name: "Apple Watch Ultra 2 49mm (LTE) Viền Titan - Dây Alpine Loop size M",
    //     price: "21.990.000 đ",
    //     CPU: 'Apple S9',
    //     RAM: null,
    //     doPhanGiai: null,
    //     kichThuocMan: '1.92 inch',
    //     DLpin: null,
    //     trongLuong: null,
    //     kichThuoc: '49 x 44 x 14.4 mm'
    // },
    {
        type: 'Watch',
        id: '017',
        imgURL: Apple_Watch_Ultra_2_49_mm_LTE_Viền_Titan_Dây_Alpine_Loop_size_S_didongviet,
        name: "Apple Watch Ultra 2 49mm (LTE) Viền Titan - Dây Alpine Loop size S",
        price: "21.990.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.92 inch',
        DLpin: 'Lên đến 36 giờ - Lên đến 72 giờ ở Chế Độ Nguồn Điện Thấp',
        trongLuong: null,
        kichThuoc: '49 x 44 x 14.4 mm'
    },
    {
        type: 'Watch',
        id: '018',
        imgURL: Apple_Watch_Ultra_2_49_mm_LTE_Viền_Titan_Dây_Trail_Loop_size_M_L_didongviet,
        name: "Apple Watch Ultra 2 49mm (LTE) Viền Titan - Dây Trail Loop size M/L",
        price: "21.990.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.92 inches',
        DLpin: null,
        trongLuong: null,
        kichThuoc: '49 x 44 x 14.4 mm'
    },
    {
        type: 'Watch',
        id: '019',
        imgURL: Apple_Watch_Ultra_2_49_mm_LTE_Viền_Titan_Dây_Trail_Loop_size_S_M_didongviet,
        name: "Apple Watch Ultra 2 49mm (LTE) Viền Titan - Dây Trail Loop size S/M",
        price: "21.990.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.92 inches',
        DLpin: null,
        trongLuong: null,
        kichThuoc: null
    },
    {
        type: 'Watch',
        id: '020',
        imgURL: Apple_Watch_Ultra2_49_mm_LTE_Viền_Titan_Dây_Ocean_didongviet,
        name: "Apple Watch Ultra 2 49mm (LTE) Viền Titan - Dây Ocean",
        price: "21.990.000 đ",
        CPU: 'Apple S9',
        RAM: null,
        doPhanGiai: null,
        kichThuocMan: '1.92 inches',
        DLpin: null,
        trongLuong: null,
        kichThuoc: '49 x 44 x 14.4 mm'
    },
];